# Gunakan image Nginx resmi sebagai base image
FROM nginx:latest

# Salin file index.html ke dalam direktori default Nginx
COPY . /usr/share/nginx/html/
# COPY nginx/default.conf /etc/nginx/conf.d/default.conf