version: '3.8'
services:
  alert_chat_app:
    container_name: alert_chat_app
    build:
      context: ./server
      dockerfile: Dockerfile
    image: alert_chat_app
    ports:
      - "80:80"
  
    
  